### ISSUE TITLE
install error on xformers

### ISSUE THREAD

**Issue by zsutomato** [deforum-art/deforum-stable-diffusion#177]
ERROR: Wheel 'xformers' located at C:\Users\zsuto\AppData\Local\Temp\pip-unpack-gpz0y14d\xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl is invalid.

Got this msg when I tried to run the "python install_requirements.py", any idea?

**Comment by GwendalC** [comment]
Got it too 👍 Please help us :)

**Comment by sergree** [comment]
Same here.

**Comment by sergree** [comment]
It seems it is related to wrong xformers package size - few kb instead of 90+ mb (maybe Git LFS issue)..
But when i downloaded it manually and run it again it gives me new error:

`RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?`

**Comment by vibes24** [comment]
Dev have not responded to this in over 2 weeks? Anybody got a solution for this?

**Comment by xxloubexx** [comment]
You can use this pull request which is working fine : https://github.com/deforum-art/deforum-stable-diffusion/pull/196
You'll need to recreate your conda environment.

**Comment by ailton07** [comment]
How I fixed:
1. Download https://huggingface.co/deforum/xformers/blob/main/windows/xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl 
2. Install it using `pip install ~/Downloads/xformers-0.0.15.dev0fd21b40.d20230107-cp310-cp310-win_amd64.whl `
3. Comment `install_requirements.py` line 85 (`pip_install_packages(xformers)`)
