### ISSUE TITLE
Readme - Installing confusion

### ISSUE THREAD

**Issue by vibes24** [deforum-art/deforum-stable-diffusion#195]
Getting Started
To install Deforum Stable Diffusion, follow these steps:
`
1. Create a suitable anaconda environment for Deforum and activate it:
conda create -n dsd python=3.10 -y
conda activate dsd
2. Clone this github repository and navigate to it:
git clone https://github.com/deforum-art/deforum-stable-diffusion.git
cd deforum-stable-diffusion
Install required packages with the install script:
python install_requirements.py
Check your installation by running the Python script:
python Deforum_Stable_Diffusion.py
`

git is not a valid command in DSD environment. Do you mean I need to "exit" and re-open anaconda cmd to proceed with the rest of the installation? 
I'm just worried that I'll be installing stuff outside the environment?

Is there a certain step to do before step 2?

**Comment by vibes24** [comment]
Another confusion.

**Running deforum**
`python Deforum_Stable_Diffusion.py`

Is the web server supposed to open by itself? How do I connect to the server locally? I saw on youtube the address is 127.0.0.1:7680 but it's not responding for me. How do we access DSD after running it?

**Comment by Vendaciousness** [comment]
You should consider reading some articles or watching a YouTube videos on how to install Automatic1111. They cover all of this basic stuff. You really shouldn't be opening a bug report because you couldn't figure out how to use it. The software runs just fine if you take 5 minutes to watch a how-to video. Please close the bug, so the devs can concentrate on actual bugs that prevent the software from running or functioni8ng properly.
