### ISSUE TITLE
Support for Stable Diffusion 2.0

### ISSUE THREAD

**Issue by eran-sefirot** [deforum-art/deforum-stable-diffusion#56]
Hey,
Thanks for this amazing art framework!

Does the framework support stable diffusion 2.0?
I am trying to render animation using the existing framework but experience some weird behaviour 

Thanks

**Comment by kabachuha** [comment]
The dev branch https://github.com/deforum-art/deforum-stable-diffusion/tree/dev should have support for 2.0, but there are some bugs reported

**Comment by eran-sefirot** [comment]
What changed ? I mean migration from 1.4 to 1.5 was smooth..

Thanks I’ll deploy it to our dev servers.

**Comment by kabachuha** [comment]
The default resolution moved from 768^2 to 512^2 in 2.0 which helped many spatially complex things such as hands, wings, realistic landscapes, machinery or jewelry. Its main downside is dataset shrinking due to potential legal troubles, StabilityAI removed many the living artists from the database as well as any potential nsfw content. But I'm sure there will be a plenty of finetuned 2.0 derivatives extremely soon

**Comment by theguaz** [comment]
Suscribed to this, specially interested into using the new 512-depth-ema.ckpt model with each frame of an extraction from video :)

**Comment by deforum** [comment]
added
